name: .NET Core

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    
    - name: Configure GitVersion
      run: 'echo "mode: Mainline" >> GitVersion.yml'
      
    - name: Run GitVersion
      id: gitversion
      uses: roryprimrose/rungitversion@v1.0.0
      #with:
        # "true" to use GitVersion /nofetch, any other value to enable fetch
        #nofetch: # default is false
        # "true" to use GitVersion /nocache, any other value to enable cache
        #nocache: # default is false  
      
    
    
    - run: |
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
        
    - name: Update project version
      uses: roryprimrose/set-vs-sdk-project-version@v1
      with:
        projectFilter: '**/*.csproj'
        version: ${{ steps.gitversion.outputs.NuGetVersionV2 }}
        assemblyVersion: ${{ steps.gitversion.outputs.AssemblySemVer }}
        fileVersion: ${{ steps.gitversion.outputs.MajorMinorPatch }}
        informationalVersion: ${{ steps.gitversion.outputs.InformationalVersion }}    
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - run: dotnet nuget add source https://nuget.pkg.github.com/openelt/index.json -n github -u openelt -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    - name: Install dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: src
    - run: dotnet pack
      working-directory: src/OpenELT.Interfaces
      
    - uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
        nupkg-path:  '**/*.nupkg'
        repo-owner:  'openelt'
        gh-user:  'openelt'
        token:  ${{ secrets.GITHUB_TOKEN }}
    
 
